version: "3"

services:

  unimus:
    image: croc/unimus
    container_name: unimus
    depends_on:
      - unimus-db
    ports:
      - "8085:8085"
    volumes:
      - ./config:/etc/unimus
    entrypoint:
      - /opt/start.sh

